config/routes.rb
Rails.application.routes.draw do
  resources :schedules
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #get '/' => 'users#index'
  #post '/sessions' => 'sessions#create'
  #post '/users' => 'users#create'
  #get '/dashboard' => 'schedules#index'
  get 'search' => "schedules#search"
  get 'schedules/show' => 'schedules#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
	validates :room, numericality: true

	def self.search_by(search_term)
		where("LOWER(name) LIKE :search_term",search_term: "%#{search_term.downcase}%")
	end

	

	def self.search(search)
	  where("title LIKE ? OR day LIKE ? OR lecture LIKE ? OR room LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%") 
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all
    if params[:search]
    @schedules = Schedule.search(params[:search]).order("created_at DESC")
    #schedules = Schedule.search(params[:search])
  else
    @schedules = Schedule.all.order("created_at DESC")
  end
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
    #@schedules = Schedule.all
  end

  def search
    #Viewのformで取得したパラメータをモデルに渡す
    #@schedules = Schedule.search(params[:search])
  end


  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end


  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def schedule_params
      params.require(:schedule).permit(:title, :day, :lecture, :room)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kadai1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    
    
    <%= yield %>
    
  </body>
</html>

app/views/schedules/_form.html.erb
<%= form_with(model: schedule, local: true) do |form| %>
  <% if schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
        <% schedule.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class ="container">
  <div class="field form-group">
    <%= form.label :科目名 %><br>
    <%= form.text_area :title, class: 'form-control' %>
  </div>

  <div class="field form-check">
    <h4><%= form.label :曜日 %></h4>
    <%= form.check_box :day, {multiple: false}, "月", nil %>月
    <%= form.check_box :day, {multiple: false}, "火", nil %>火
    <%= form.check_box :day, {multiple: false}, "水", nil %>水
    <%= form.check_box :day, {multiple: false}, "木", nil %>木
    <%= form.check_box :day, {multiple: false}, "金", nil %>金
  </div><br>

  <div class="field">
    <h4><%= form.label :限目 %></h4>
    <%= form.check_box :lecture, {multiple: false}, "1限", nil %>1限
    <%= form.check_box :lecture, {multiple: false}, "2限", nil %>2限
    <%= form.check_box :lecture, {multiple: false}, "3限", nil %>3限
    <%= form.check_box :lecture, {multiple: false}, "4限", nil %>4限
    <%= form.check_box :lecture, {multiple: false}, "5限", nil %>5限
  </div><br>

  <div class="field form-group">
    <%= form.label :教室 %><br>
    <%= form.text_field :room, class: 'form-control' %>
  </div>


  <div class="actions">
    <%= form.submit '作成', class: 'btn btn-warning' %>
  </div><br>

  <%= link_to '表示', @schedule, class: 'btn btn-primary' %>
  <%= link_to '戻る', schedules_path, class: 'btn btn-info' %>
</div>

<% end %>

app/views/schedules/edit.html.erb
<div class="container">
<h1 class="text-danger">Editing Schedule</h1><hr>
</div>




<%= render 'form', schedule: @schedule %><br>

app/views/schedules/new.html.erb
<div class="container">
	<h1 class="text-primary">New Schedule</h1><hr>
</div>

<%= render 'form', schedule: @schedule %><br>

app/views/schedules/search.html.erb
<p>検索</p>
<%= form_tag(search_path,:method => 'get') do %>
  <%= text_field_tag :search %>
  <%= submit_tag 'Search', :name => nil %>
<% end %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
<h1 style="color: green;">授業の情報</h1><hr><br>


  <ul class="list-group">
    <li class="list-group-item">
    		<strong>Title:</strong>
    		<%= @schedule.title %></li>
    <li class="list-group-item">
    		<strong>Day:</strong>
    		<%= @schedule.day %></li>
    <li class="list-group-item">
    		<strong>Lecture:</strong>
    		<%= @schedule.lecture %></li>
    <li class="list-group-item">
    		  <strong>Room:</strong>
    			<%= @schedule.room %></li>
  </ul>




<%= link_to '編集', edit_schedule_path(@schedule), class: 'btn btn-warning btn' %> 
<%= link_to '戻る', schedules_path, class: 'btn btn-info' %>
</div>